// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/iam.CurrentUserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/families/consent": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "families"
                ],
                "summary": "Get COPPA consent status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/iam.ConsentStatusResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "families"
                ],
                "summary": "Submit COPPA consent",
                "parameters": [
                    {
                        "description": "Consent details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iam.CoppaConsentCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/iam.ConsentStatusResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/families/methodology": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "families"
                ],
                "summary": "Update family methodology selection",
                "parameters": [
                    {
                        "description": "Methodology selection",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/method.UpdateMethodologyCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/method.MethodologySelectionResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/families/profile": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "families"
                ],
                "summary": "Get family profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/iam.FamilyProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "families"
                ],
                "summary": "Update family profile",
                "parameters": [
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iam.UpdateFamilyCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/iam.FamilyProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/families/students": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "List family students",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/iam.StudentResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "Create student profile",
                "parameters": [
                    {
                        "description": "Student details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iam.CreateStudentCommand"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/iam.StudentResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/families/students/{id}": {
            "delete": {
                "tags": [
                    "students"
                ],
                "summary": "Delete student profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "Update student profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iam.UpdateStudentCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/iam.StudentResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/families/students/{id}/tools": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "families"
                ],
                "summary": "Get student's resolved tool set",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/method.ActiveToolResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/families/tools": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "families"
                ],
                "summary": "Get family's resolved active tool set",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/method.ActiveToolResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.HealthResponse"
                        }
                    }
                }
            }
        },
        "/hooks/kratos/post-login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hooks"
                ],
                "summary": "Kratos post-login webhook",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/hooks/kratos/post-registration": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hooks"
                ],
                "summary": "Kratos post-registration webhook",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/methodologies": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "methodologies"
                ],
                "summary": "List active methodologies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/method.MethodologySummaryResponse"
                            }
                        }
                    }
                }
            }
        },
        "/methodologies/{slug}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "methodologies"
                ],
                "summary": "Get methodology detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Methodology slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/method.MethodologyDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/methodologies/{slug}/tools": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "methodologies"
                ],
                "summary": "List tools for a methodology",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Methodology slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/method.ActiveToolResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "iam.ConsentStatusResponse": {
            "type": "object",
            "properties": {
                "can_create_students": {
                    "type": "boolean"
                },
                "consent_method": {
                    "type": "string"
                },
                "consented_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "iam.CoppaConsentCommand": {
            "type": "object",
            "required": [
                "coppa_notice_acknowledged",
                "method",
                "verification_token"
            ],
            "properties": {
                "coppa_notice_acknowledged": {
                    "type": "boolean"
                },
                "method": {
                    "type": "string"
                },
                "verification_token": {
                    "type": "string"
                }
            }
        },
        "iam.CreateStudentCommand": {
            "type": "object",
            "required": [
                "display_name"
            ],
            "properties": {
                "birth_year": {
                    "type": "integer",
                    "maximum": 2030,
                    "minimum": 2000
                },
                "display_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "grade_level": {
                    "type": "string",
                    "maxLength": 20
                },
                "methodology_override_id": {
                    "type": "string"
                }
            }
        },
        "iam.CurrentUserResponse": {
            "type": "object",
            "properties": {
                "coppa_consent_status": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "family_display_name": {
                    "type": "string"
                },
                "family_id": {
                    "type": "string"
                },
                "is_primary_parent": {
                    "type": "boolean"
                },
                "parent_id": {
                    "type": "string"
                },
                "subscription_tier": {
                    "type": "string"
                }
            }
        },
        "iam.FamilyProfileResponse": {
            "type": "object",
            "properties": {
                "coppa_consent_status": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "location_region": {
                    "type": "string"
                },
                "parents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/iam.ParentSummary"
                    }
                },
                "primary_methodology_id": {
                    "type": "string"
                },
                "secondary_methodology_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "state_code": {
                    "type": "string"
                },
                "student_count": {
                    "type": "integer"
                },
                "subscription_tier": {
                    "type": "string"
                }
            }
        },
        "iam.ParentSummary": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_primary": {
                    "type": "boolean"
                }
            }
        },
        "iam.StudentResponse": {
            "type": "object",
            "properties": {
                "birth_year": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "grade_level": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "methodology_override_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "iam.UpdateFamilyCommand": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "location_region": {
                    "type": "string",
                    "maxLength": 200
                },
                "state_code": {
                    "type": "string"
                }
            }
        },
        "iam.UpdateStudentCommand": {
            "type": "object",
            "properties": {
                "birth_year": {
                    "type": "integer",
                    "maximum": 2030,
                    "minimum": 2000
                },
                "display_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "grade_level": {
                    "type": "string",
                    "maxLength": 20
                },
                "methodology_override_id": {
                    "type": "string"
                }
            }
        },
        "method.ActiveToolResponse": {
            "type": "object",
            "properties": {
                "config_overrides": {
                    "type": "object"
                },
                "description": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "guidance": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "sort_order": {
                    "type": "integer"
                },
                "tier": {
                    "type": "string"
                },
                "tool_id": {
                    "type": "string"
                }
            }
        },
        "method.MethodologyDetailResponse": {
            "type": "object",
            "properties": {
                "community_config": {
                    "type": "object"
                },
                "display_name": {
                    "type": "string"
                },
                "icon_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mastery_paths": {
                    "type": "object"
                },
                "onboarding_config": {
                    "type": "object"
                },
                "philosophy": {
                    "type": "object"
                },
                "short_desc": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "terminology": {
                    "type": "object"
                }
            }
        },
        "method.MethodologySelectionResponse": {
            "type": "object",
            "properties": {
                "active_tool_count": {
                    "type": "integer"
                },
                "primary": {
                    "$ref": "#/definitions/method.MethodologySummaryResponse"
                },
                "secondary": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/method.MethodologySummaryResponse"
                    }
                }
            }
        },
        "method.MethodologySummaryResponse": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "icon_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "short_desc": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "method.UpdateMethodologyCommand": {
            "type": "object",
            "required": [
                "primary_methodology_id"
            ],
            "properties": {
                "primary_methodology_id": {
                    "type": "string"
                },
                "secondary_methodology_ids": {
                    "type": "array",
                    "maxItems": 5,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "shared.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "shared.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/shared.ErrorBody"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:3500",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Homegrown Academy API",
	Description:      "API for the Homegrown Academy homeschooling platform",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
