// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/iam.CurrentUserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/discovery/quiz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discovery"
                ],
                "summary": "Get active quiz",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/discover.QuizResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/discovery/quiz/results": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discovery"
                ],
                "summary": "Submit quiz answers and get methodology recommendations",
                "parameters": [
                    {
                        "description": "Quiz answers",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/discover.SubmitQuizCommand"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/discover.QuizResultResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/discovery/quiz/results/{share_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discovery"
                ],
                "summary": "Get quiz result by share ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Share ID",
                        "name": "share_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/discover.QuizResultResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/discovery/state-guides": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discovery"
                ],
                "summary": "List all state guides",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/discover.StateGuideSummaryResponse"
                            }
                        }
                    }
                }
            }
        },
        "/discovery/state-guides/{state_code}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discovery"
                ],
                "summary": "Get state guide by state code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Two-letter state code (e.g. CA, NY)",
                        "name": "state_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/discover.StateGuideResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/families/consent": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "families"
                ],
                "summary": "Get COPPA consent status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/iam.ConsentStatusResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "families"
                ],
                "summary": "Submit COPPA consent",
                "parameters": [
                    {
                        "description": "Consent details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iam.CoppaConsentCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/iam.ConsentStatusResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/families/methodology": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "families"
                ],
                "summary": "Update family methodology selection",
                "parameters": [
                    {
                        "description": "Methodology selection",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/method.UpdateMethodologyCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/method.MethodologySelectionResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/families/profile": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "families"
                ],
                "summary": "Get family profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/iam.FamilyProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "families"
                ],
                "summary": "Update family profile",
                "parameters": [
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iam.UpdateFamilyCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/iam.FamilyProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/families/students": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "List family students",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/iam.StudentResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "Create student profile",
                "parameters": [
                    {
                        "description": "Student details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iam.CreateStudentCommand"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/iam.StudentResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/families/students/{id}": {
            "delete": {
                "tags": [
                    "students"
                ],
                "summary": "Delete student profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "Update student profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iam.UpdateStudentCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/iam.StudentResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/families/students/{id}/tools": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "families"
                ],
                "summary": "Get student's resolved tool set",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/method.ActiveToolResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/families/tools": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "families"
                ],
                "summary": "Get family's resolved active tool set",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/method.ActiveToolResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.HealthResponse"
                        }
                    }
                }
            }
        },
        "/hooks/kratos/post-login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hooks"
                ],
                "summary": "Kratos post-login webhook",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/hooks/kratos/post-registration": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hooks"
                ],
                "summary": "Kratos post-registration webhook",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/methodologies": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "methodologies"
                ],
                "summary": "List active methodologies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/method.MethodologySummaryResponse"
                            }
                        }
                    }
                }
            }
        },
        "/methodologies/{slug}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "methodologies"
                ],
                "summary": "Get methodology detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Methodology slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/method.MethodologyDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/methodologies/{slug}/tools": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "methodologies"
                ],
                "summary": "List tools for a methodology",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Methodology slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/method.ActiveToolResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/onboarding/children": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Add child during onboarding",
                "parameters": [
                    {
                        "description": "Child details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/onboard.AddChildCommand"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/onboard.WizardProgressResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/onboarding/children/{id}": {
            "delete": {
                "tags": [
                    "onboarding"
                ],
                "summary": "Remove child during onboarding",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/onboarding/community": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Get onboarding community suggestions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/onboard.CommunityResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/onboarding/complete": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Complete the onboarding wizard",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/onboard.WizardProgressResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/onboarding/family-profile": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Update family profile during onboarding",
                "parameters": [
                    {
                        "description": "Profile fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/onboard.UpdateFamilyProfileCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/onboard.WizardProgressResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/onboarding/methodology": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Select methodology during onboarding",
                "parameters": [
                    {
                        "description": "Methodology selection",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/onboard.SelectMethodologyCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/onboard.WizardProgressResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/onboarding/methodology/import-quiz": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Import quiz result into onboarding",
                "parameters": [
                    {
                        "description": "Quiz share ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/onboard.ImportQuizCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/onboard.QuizImportResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/onboarding/progress": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Get onboarding wizard progress",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/onboard.WizardProgressResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/onboarding/recommendations": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Get onboarding starter recommendations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/onboard.RecommendationsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/onboarding/roadmap": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Get onboarding roadmap",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/onboard.RoadmapResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/onboarding/skip": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Skip the onboarding wizard",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/onboard.WizardProgressResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "discover.MethodologyRecommendation": {
            "type": "object",
            "properties": {
                "explanation": {
                    "type": "string"
                },
                "methodology_name": {
                    "type": "string"
                },
                "methodology_slug": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "score_percentage": {
                    "type": "integer"
                }
            }
        },
        "discover.QuizAnswerResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "discover.QuizQuestionResponse": {
            "type": "object",
            "properties": {
                "answers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/discover.QuizAnswerResponse"
                    }
                },
                "category": {
                    "type": "string"
                },
                "help_text": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "discover.QuizResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/discover.QuizQuestionResponse"
                    }
                },
                "quiz_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "discover.QuizResultResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "is_claimed": {
                    "type": "boolean"
                },
                "quiz_version": {
                    "type": "integer"
                },
                "recommendations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/discover.MethodologyRecommendation"
                    }
                },
                "share_id": {
                    "type": "string"
                }
            }
        },
        "discover.StateGuideRequirements": {
            "type": "object",
            "properties": {
                "assessment_details": {
                    "type": "string"
                },
                "assessment_required": {
                    "type": "boolean"
                },
                "attendance_days": {
                    "type": "integer"
                },
                "attendance_details": {
                    "type": "string"
                },
                "attendance_required": {
                    "type": "boolean"
                },
                "notification_details": {
                    "type": "string"
                },
                "notification_required": {
                    "type": "boolean"
                },
                "record_keeping_details": {
                    "type": "string"
                },
                "record_keeping_required": {
                    "type": "boolean"
                },
                "regulation_level": {
                    "description": "\"low\"|\"moderate\"|\"high\"",
                    "type": "string"
                },
                "required_subjects": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "umbrella_school_available": {
                    "type": "boolean"
                },
                "umbrella_school_details": {
                    "type": "string"
                }
            }
        },
        "discover.StateGuideResponse": {
            "type": "object",
            "properties": {
                "guide_content": {
                    "type": "string"
                },
                "last_reviewed_at": {
                    "type": "string"
                },
                "legal_disclaimer": {
                    "type": "string"
                },
                "requirements": {
                    "$ref": "#/definitions/discover.StateGuideRequirements"
                },
                "state_code": {
                    "type": "string"
                },
                "state_name": {
                    "type": "string"
                }
            }
        },
        "discover.StateGuideSummaryResponse": {
            "type": "object",
            "properties": {
                "is_available": {
                    "type": "boolean"
                },
                "last_reviewed_at": {
                    "type": "string"
                },
                "state_code": {
                    "type": "string"
                },
                "state_name": {
                    "type": "string"
                }
            }
        },
        "discover.SubmitQuizCommand": {
            "type": "object",
            "required": [
                "answers"
            ],
            "properties": {
                "answers": {
                    "description": "Answers maps question_id → answer_id.\nMissing questions contribute zero weight (partial submissions are valid).",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "session_token": {
                    "type": "string",
                    "maxLength": 128
                }
            }
        },
        "iam.ConsentStatusResponse": {
            "type": "object",
            "properties": {
                "can_create_students": {
                    "type": "boolean"
                },
                "consent_method": {
                    "type": "string"
                },
                "consented_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "iam.CoppaConsentCommand": {
            "type": "object",
            "required": [
                "coppa_notice_acknowledged",
                "method",
                "verification_token"
            ],
            "properties": {
                "coppa_notice_acknowledged": {
                    "type": "boolean"
                },
                "method": {
                    "type": "string"
                },
                "verification_token": {
                    "type": "string"
                }
            }
        },
        "iam.CreateStudentCommand": {
            "type": "object",
            "required": [
                "display_name"
            ],
            "properties": {
                "birth_year": {
                    "type": "integer",
                    "maximum": 2030,
                    "minimum": 2000
                },
                "display_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "grade_level": {
                    "type": "string",
                    "maxLength": 20
                },
                "methodology_override_slug": {
                    "type": "string"
                }
            }
        },
        "iam.CurrentUserResponse": {
            "type": "object",
            "properties": {
                "coppa_consent_status": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "family_display_name": {
                    "type": "string"
                },
                "family_id": {
                    "type": "string"
                },
                "is_primary_parent": {
                    "type": "boolean"
                },
                "parent_id": {
                    "type": "string"
                },
                "subscription_tier": {
                    "type": "string"
                }
            }
        },
        "iam.FamilyProfileResponse": {
            "type": "object",
            "properties": {
                "coppa_consent_status": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "location_region": {
                    "type": "string"
                },
                "parents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/iam.ParentSummary"
                    }
                },
                "primary_methodology_slug": {
                    "type": "string"
                },
                "secondary_methodology_slugs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "state_code": {
                    "type": "string"
                },
                "student_count": {
                    "type": "integer"
                },
                "subscription_tier": {
                    "type": "string"
                }
            }
        },
        "iam.ParentSummary": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_primary": {
                    "type": "boolean"
                }
            }
        },
        "iam.StudentResponse": {
            "type": "object",
            "properties": {
                "birth_year": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "grade_level": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "methodology_override_slug": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "iam.UpdateFamilyCommand": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "location_region": {
                    "type": "string",
                    "maxLength": 200
                },
                "state_code": {
                    "type": "string"
                }
            }
        },
        "iam.UpdateStudentCommand": {
            "type": "object",
            "properties": {
                "birth_year": {
                    "type": "integer",
                    "maximum": 2030,
                    "minimum": 2000
                },
                "display_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "grade_level": {
                    "type": "string",
                    "maxLength": 20
                },
                "methodology_override_slug": {
                    "type": "string"
                }
            }
        },
        "method.ActiveToolResponse": {
            "type": "object",
            "properties": {
                "config_overrides": {
                    "type": "object"
                },
                "description": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "guidance": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "sort_order": {
                    "type": "integer"
                },
                "tier": {
                    "type": "string"
                }
            }
        },
        "method.MethodologyDetailResponse": {
            "type": "object",
            "properties": {
                "community_config": {
                    "type": "object"
                },
                "display_name": {
                    "type": "string"
                },
                "icon_url": {
                    "type": "string"
                },
                "mastery_paths": {
                    "type": "object"
                },
                "onboarding_config": {
                    "type": "object"
                },
                "philosophy": {
                    "type": "object"
                },
                "short_desc": {
                    "type": "string"
                },
                "slug": {
                    "$ref": "#/definitions/method.MethodologyID"
                },
                "terminology": {
                    "type": "object"
                }
            }
        },
        "method.MethodologyID": {
            "type": "string",
            "enum": [
                "charlotte-mason",
                "traditional",
                "classical",
                "waldorf",
                "montessori",
                "unschooling"
            ],
            "x-enum-varnames": [
                "MethodologyCharlotteMason",
                "MethodologyTraditional",
                "MethodologyClassical",
                "MethodologyWaldorf",
                "MethodologyMontessori",
                "MethodologyUnschooling"
            ]
        },
        "method.MethodologySelectionResponse": {
            "type": "object",
            "properties": {
                "active_tool_count": {
                    "type": "integer"
                },
                "primary": {
                    "$ref": "#/definitions/method.MethodologySummaryResponse"
                },
                "secondary": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/method.MethodologySummaryResponse"
                    }
                }
            }
        },
        "method.MethodologySummaryResponse": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "icon_url": {
                    "type": "string"
                },
                "short_desc": {
                    "type": "string"
                },
                "slug": {
                    "$ref": "#/definitions/method.MethodologyID"
                }
            }
        },
        "method.UpdateMethodologyCommand": {
            "type": "object",
            "required": [
                "primary_methodology_slug"
            ],
            "properties": {
                "primary_methodology_slug": {
                    "$ref": "#/definitions/method.MethodologyID"
                },
                "secondary_methodology_slugs": {
                    "type": "array",
                    "maxItems": 5,
                    "items": {
                        "$ref": "#/definitions/method.MethodologyID"
                    }
                }
            }
        },
        "onboard.AddChildCommand": {
            "type": "object",
            "required": [
                "display_name"
            ],
            "properties": {
                "birth_year": {
                    "type": "integer",
                    "maximum": 2030,
                    "minimum": 2000
                },
                "display_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "grade_level": {
                    "type": "string",
                    "maxLength": 20
                }
            }
        },
        "onboard.CommunityResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/onboard.CommunitySuggestionResponse"
                    }
                }
            }
        },
        "onboard.CommunitySuggestionResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "methodology_slug": {
                    "type": "string"
                },
                "reference_id": {
                    "type": "string"
                },
                "sort_order": {
                    "type": "integer"
                },
                "suggestion_type": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "onboard.ImportQuizCommand": {
            "type": "object",
            "required": [
                "share_id"
            ],
            "properties": {
                "share_id": {
                    "type": "string"
                }
            }
        },
        "onboard.OnboardQuizRecommendation": {
            "type": "object",
            "properties": {
                "explanation": {
                    "type": "string"
                },
                "methodology_name": {
                    "type": "string"
                },
                "methodology_slug": {
                    "type": "string"
                },
                "score_percentage": {
                    "type": "integer"
                }
            }
        },
        "onboard.QuizImportResponse": {
            "type": "object",
            "properties": {
                "methodology_recommendations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/onboard.OnboardQuizRecommendation"
                    }
                },
                "share_id": {
                    "type": "string"
                },
                "suggested_primary_slug": {
                    "type": "string"
                }
            }
        },
        "onboard.RecommendationAgeGroup": {
            "type": "object",
            "properties": {
                "age_group": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/onboard.RecommendationItemResponse"
                    }
                }
            }
        },
        "onboard.RecommendationItemResponse": {
            "type": "object",
            "properties": {
                "age_group": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "link_url": {
                    "type": "string"
                },
                "methodology_slug": {
                    "type": "string"
                },
                "price_type": {
                    "type": "string"
                },
                "sort_order": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "onboard.RecommendationsResponse": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/onboard.RecommendationAgeGroup"
                    }
                }
            }
        },
        "onboard.RoadmapAgeGroup": {
            "type": "object",
            "properties": {
                "age_group": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/onboard.RoadmapItemResponse"
                    }
                }
            }
        },
        "onboard.RoadmapItemResponse": {
            "type": "object",
            "properties": {
                "age_group": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_completed": {
                    "type": "boolean"
                },
                "item_type": {
                    "$ref": "#/definitions/onboard.RoadmapItemType"
                },
                "link_url": {
                    "type": "string"
                },
                "methodology_slug": {
                    "type": "string"
                },
                "sort_order": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "onboard.RoadmapItemType": {
            "type": "string",
            "enum": [
                "task",
                "resource",
                "feature_tour"
            ],
            "x-enum-varnames": [
                "ItemTypeTask",
                "ItemTypeResource",
                "ItemTypeFeatureTour"
            ]
        },
        "onboard.RoadmapResponse": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/onboard.RoadmapAgeGroup"
                    }
                }
            }
        },
        "onboard.SelectMethodologyCommand": {
            "type": "object",
            "required": [
                "methodology_path",
                "primary_methodology_slug"
            ],
            "properties": {
                "explanation_acknowledged": {
                    "type": "boolean"
                },
                "methodology_path": {
                    "type": "string",
                    "enum": [
                        "quiz_informed",
                        "exploration",
                        "skip"
                    ]
                },
                "primary_methodology_slug": {
                    "type": "string"
                },
                "secondary_methodology_slugs": {
                    "type": "array",
                    "maxItems": 5,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "onboard.UpdateFamilyProfileCommand": {
            "type": "object",
            "required": [
                "display_name"
            ],
            "properties": {
                "display_name": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1
                },
                "location_region": {
                    "type": "string",
                    "maxLength": 200
                },
                "state_code": {
                    "type": "string"
                }
            }
        },
        "onboard.WizardProgressResponse": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "type": "string"
                },
                "completed_steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/onboard.WizardStep"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "current_step": {
                    "$ref": "#/definitions/onboard.WizardStep"
                },
                "family_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "methodology_path": {
                    "type": "string"
                },
                "quiz_share_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/onboard.WizardStatus"
                }
            }
        },
        "onboard.WizardStatus": {
            "type": "string",
            "enum": [
                "in_progress",
                "completed",
                "skipped"
            ],
            "x-enum-varnames": [
                "StatusInProgress",
                "StatusCompleted",
                "StatusSkipped"
            ]
        },
        "onboard.WizardStep": {
            "type": "string",
            "enum": [
                "family_profile",
                "children",
                "methodology",
                "roadmap_review"
            ],
            "x-enum-varnames": [
                "StepFamilyProfile",
                "StepChildren",
                "StepMethodology",
                "StepRoadmapReview"
            ]
        },
        "shared.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "shared.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/shared.ErrorBody"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:3500",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Homegrown Academy API",
	Description:      "API for the Homegrown Academy homeschooling platform",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
